#!/usr/bin/env bash
# Install a nginx web server listening on port 80.
#
# Such that curl localhost returns "Hello World'.

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx start
