#!/usr/bin/env bash
# This script builds on previous scripts
#
# Also, to configure a directive so the Nginx server
# redirects to another page with 301 Moved Permenently

sudo apt-get -y update
sudo apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee file /var/www/html/index.nginx-debian.html
sudo sed -i "/listen 80 default_server/a add_header X-Served-By $hostname;" /etc/nginx/sites-available/default
sudo sed -i '/server_name _;/a \\tlocation /redirect_me {\n\t\trewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee file /var/www/html/404.html
sudo sed -i "/server_name _;/a error_page 404 /404.html;\nlocation = /404.html {\nroot /var/www/html;\ninternal;\n}" /etc/nginx/sites-available/default
sudo service nginx restart
