#!/usr/bin/env bash
# Installs and setup haproxy

sudo apt update
sudo apt install -y haproxy

haproxy_conf_file="/etc/haproxy/haproxy.cfg"

# Configure Load Balancer

# Frontend Configuration
frontend_name="frontend http"
frontend_bind="bind *:80"
frontend_mode="mode http"
frontend_default_backend="default_backend web-backend"
frontend_config="$frontend_name\n\t$frontend_bind\n\t$frontend_mode\n\t$frontend_default_backend\n"

# Backend Configuration
backend_name="backend web-backend"
backend_balance="balance roundrobin"
backend_server1="server web1 35.153.66.57:80 check"
backend_server2="server web2 35.174.211.149:80 check"
backend_config="$backend_name\n\t$backend_balance\n\t$backend_server1\n\t$backend_server2"

# Append configurations to HAProxy configuration file
sudo sed -i "$ a $frontend_config" $haproxy_conf_file
sudo sed -i "$ a $backend_config" $haproxy_conf_file

# Display success message
echo "HAProxy configuration updated successfully."

# Restart HAProxy
sudo service haproxy restart
