#!/usr/bin/env bash
# debugging nginx to listen on port 80
# The flag -s creates a symbolic link

sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
