#!/usr/bin/env bash
# symmbollic link available and enable to listen on port 80 
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo pkill -9 nginx
