#!/usr/bin/env bash
# prints diplaying "Best School" but
# "bad luck" on 4th interation and "good luck"
# on 8th iteration
i="0"
while [ $i -lt 10 ];
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
       		echo "Best School"
	fi
	i=$((i+1));
done
