#!/usr/bin/env bash
# prints decimals from 1 to 20 but
# +prints 4 and then bad luck from China for the 4th loop iteration
# +prints 9 and then bad luck from Japan for the 9th loop iteration
# +prints 17 and then bad luck from Italy for the 17th loop iteration
COUNTER=1
while [ $COUNTER -le 20 ]; do
    echo $COUNTER
    ((COUNTER++))

    case $COUNTER in
	5) echo "bad luck from China";;
	10) echo "bad luck from Japan";;
	18) echo "bad luck from Italy";;
    esac
done   
