#!/usr/bin/env bash
# Bash Script that displays all active IPv4 address
if command -v ip &> /dev/null; then
    ip -4 addr show | grep -oE "inet [0-9]+\.[0-9]+\.[0-9]+\.[0-9]+" | awk '{print $2}'
else
    ifconfig | grep -oE "inet addr:[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+" | cut -d ':' -f 2
fi
